### ISSUE TITLE
For loop for zones and endpoints take too much time for big setup

### ISSUE THREAD

**Issue by l13t** [Icinga/icinga2-diagnostics#18]
Maybe it makes sense to have some external script to proceed this data? Cause it takes ~10 seconds to generate output for configuration with ~5k services, ~400 hosts and ~15 zones.

**Comment by widhalmt** [comment]
Thanks for the feedback. I thought about having the script get an output into a temporary file and parsing this file over and over again instead of running `icinga2 object list`with different parameters. On the other hand since we're using bash it might get rather complicated to parse the output.

I thought of the script to be a slow data collector which you start only when needed and get your output after some while. I had some similar tools as a systems engineer (remember "Sun Explorer"?) It took them forever to get all the data wrapped up and that was ok because you only ran it when you wanted to send data to a support engineer when they requested it. Sun back then even had the option to schedule runs via cron so you have you output ready when you need it because it could take so long to build a new one.

I'll think about it and talk to the core developers if there was a way of speeding it up without making the script too complex.

What could be a solution is having some checks running in parallel and collecting the data in the end. Again this could make it overly complex.

**Comment by l13t** [comment]
To be fair I didn't ever use sun explorer but I can imagine :)
Yeah. You always should find the best solution between "simple tool" and "quick tool" :) .
Personally, I would write such script in python. But that causes some extra packages requirements.
Maybe there is an easy way to generate tmp file and then analyse it with sed/awk.

**Comment by widhalmt** [comment]
Yes, bash was my language of choice for 2 reasons. I think most users are at least somewhat familiar with bash so more people can contribute. But the most important reason was, as you said, to avoid any requirements.

Since we have users running Icinga 2 on Mac OS, FreeBSD and Solaris we have better chances to get the script ported in bash. I know, most platforms do have Python on board but I've seen lots of scripts using some specialities from a specific version of a scripting platform which brings even more problems when porting. So I decided to use bash. Maybe when the script get's adopted by many users and we get more feedback to use another language a rewrite might not be that complicated.

**Comment by l13t** [comment]
Whoaaa... MacOS?
Yeah. In this case makes sense. But from the other side bash is not default shell in FreeBSD (if they didn't change this since I last installed it), Alpine etc. Yes, in ~95% people install bash. But other 5% have something different. I'm not trying to say it's the wrong choice. :)
I'll try to look into script later and find a way to improve this.

**Comment by widhalmt** [comment]
Yes, AFAIK one of the core developers uses MacOS for some testbuilds, etc.
Even when bash isn't the default shell, it's available on almost any *nix system, so I hope it will work everywhere where Icinga 2 runs.
Thank you, any help is appreciated.

**Comment by dnsmichi** [comment]
Actually, 3 core developers build Icinga 2 natively on macOS (hi). Atm there isn't an app or homebrew/macports package, since there's no need. Still, it is a valid Unix platform you need to take into account. A better example: NetBSD, OpenBSD and FreeBSD all provide Icinga 2 in their ports tree. Solaris is in the making to be upstreamed in OpenIndiana - you need to take care about them too.

**Comment by widhalmt** [comment]
@dnsmichi thanks for the list. I opened #23 #24 #25 and #26 to not forget. I haven't added Mac OS because I don't see a need right now until there is support for running it in production. If you think otherwise feel free to open an issue. :-)

**Comment by widhalmt** [comment]
@l13t I now have a version which does not print out all zones in standard mode. You have to add the `-z` option to still have the zone output. In full mode the zones will be checked no matter if you add `-z` or not.
Is this what you were looking for or should we keep this issue open and go for parsing a temporary file instead?

**Comment by l13t** [comment]
I think you can close an issue atm.

**Comment by widhalmt** [comment]
Ok, thanks for the feedback.
