### ISSUE TITLE
If zone name contain spaces script split it

### ISSUE THREAD

**Issue by l13t** [Icinga/icinga2-diagnostics#19]

**Comment by widhalmt** [comment]
Thanks for the hint. I'll look into it. My testing setup had only single word zone names by now.

**Comment by l13t** [comment]
Yeah. In usual setup zone name have no spaces in name. But because of our migration to agents some dummy hosts atm defined as zones. And it caused this issue.

**Comment by widhalmt** [comment]
I'm quite sure there are more users to use whitespaces in their zone names especially with director. And since it's supported, the script should cover it. So I implemented a way of dealing with whitespaces. Thanks for reporting.

@l13t Could you pull the new version of the script and run a test on your setup?

**Comment by l13t** [comment]
Yeah, wokrs correct now (:

**Comment by widhalmt** [comment]
Cool, thanks.
