### ISSUE TITLE
Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by deric** [Icinga/icinga2-diagnostics#94]
I'm having troubles running the script:
```
./icinga-diagnostics.sh: 185: ./icinga-diagnostics.sh: Syntax error: redirection unexpected
```
A fix is surprisingly easy, changing the shebang should ensure that the script gets executed by `bash`:
```bash
#!/bin/bash
```

**Comment by widhalmt** [comment]
Hi, thanks for reporting this issue.

We opted to use `sh` instead of `bash` to allow this script to run on every operating system which is supported by Icinga (and even a bit more). I'll try to fix it but we are currently working on a rewrite in Python which should work on all OS'es we want nevertheless.

**Comment by deric** [comment]
Right, meanwhile you might replace the redirection operator `<<<` by syntax that is commonly supported. E.g. `dash` won't support `<<<` and while you're keeping `/bin/sh` you don't know which shell will be used.

**Comment by widhalmt** [comment]
Yep, you're totally right. I'll try to find a way that works on different shells.

**Comment by lazyfrosch** [comment]
So should we switch to bash for now?

**Comment by widhalmt** [comment]
I think it's ok for now to switch to bash. As for now there are several parallel projects running to check if we should rewrite it in python or replace it with another tool, so switching to bash might be the most straight-forward method to get this going again.
